version: "3"

services:
  forwardsms:
    image:  ghcr.io/scjtqs2/forwardsms/forwardsms:latest
    environment:
      - FORWARD_SECRET=your_shared_secret_here
      - TZ=Asia/Shanghai
      - HTTP_PORT=8080
    volumes:
      - ./data:/data
    restart: always
    expose:
      - 8080


  gammu-web:
    image: ghcr.io/scjtqs2/gammu-web:latest
    environment:
      - FORWARD_ENABLED=1
      - FORWARD_URL=http://forwardsms:8080/api/v1/sms/receive
      - FORWARD_SECRET=your_shared_secret_here
      - TZ=Asia/Shanghai
      - PHONE_ID=SMS1_123456789
      - ATCONNECTION=at115200
      - USB_PORT=/dev/ttyUSB3
      - API_PORT=21234
      - API_TOKEN=your_shared_token_here
    volumes:
      - ./data:/data
    privileged: true
    devices:
      - /dev/ttyUSB3
    restart: always
    ports:
      - 21234:21234
