version: "3"

services:
  forwardsms:
    image:  ghcr.io/scjtqs2/forwardsms:latest
    volumes:
      - ./data:/data
    restart: always

  gammu-smsd:
    image: ghcr.io/scjtqs2/gammu-smsd:latest
    volumes:
      - ./data:/data
      - /dev/ttyUSB3:/dev/ttyUSB3
    privileged: true
    restart: always