FROM golang:1.25-alpine AS build-env
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
#
# RUN go env -w GOPROXY="http://goproxy.cn,direct"

WORKDIR /go
COPY ./forwardsms/ /go/
# RUN apk add build-base
RUN CGO_ENABLED=0 go build -ldflags "-s -w"

FROM alpine
# 设置上海时区
RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata
COPY  --from=build-env /go/forwardsms /forwardsms

ENV HTTP_PORT="8080"
ENV FORWARD_SECRET=""

ENTRYPOINT ["/forwardsms"]