name: build_image

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          #password: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GIT_TOKEN }}
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # forwardsms metadata
      - name: Extract metadata for forwardsms
        id: meta_forwardsms
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/forwardsms
          tags: |
            type=edge
            type=ref,event=branch
            type=sha
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}

      - name: 编译 forwardsms 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: forwardsms/dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_forwardsms.outputs.tags }}
          labels: ${{ steps.meta_forwardsms.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      # gammu-smsd metadata
      - name: Extract metadata for gammu-smsd
        id: meta_gammu
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/gammu-smsd
          tags: |
            type=edge
            type=ref,event=branch
            type=sha
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}

      - name: 编译 gammu-smsd 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: gammu-smsd/dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_gammu.outputs.tags }}
          labels: ${{ steps.meta_gammu.outputs.labels }}
          platforms: linux/amd64,linux/arm64